/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progetto_2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.NoSuchPaddingException;

/**
 *
 * @author vimat
 */
public class GUI extends javax.swing.JFrame {

    private void enableFirma(){
        DSASelect.setEnabled(true);
        dimDSASelect.setEnabled(true);
        hashSelect.setEnabled(false);
        macSelect.setEnabled(false);
    }
    private void enableMac(){
        DSASelect.setEnabled(false);
        dimDSASelect.setEnabled(false);
        hashSelect.setEnabled(false);
        macSelect.setEnabled(true);
    }
    private void enableHash(){
        DSASelect.setEnabled(false);
        dimDSASelect.setEnabled(false);
        hashSelect.setEnabled(true);
        macSelect.setEnabled(false);
    }
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
   
        firmaRadio.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                enableFirma();

            }
        });
        HashRadio.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                enableHash();

            }
        });
        MACRadio.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                enableMac();

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        codificaMSelect = new javax.swing.JComboBox<>();
        modiSelect = new javax.swing.JComboBox<>();
        dimRSASelect = new javax.swing.JComboBox<>();
        paddingRSASelect = new javax.swing.JComboBox<>();
        hashSelect = new javax.swing.JComboBox<>();
        macSelect = new javax.swing.JComboBox<>();
        dimDSASelect = new javax.swing.JComboBox<>();
        DSASelect = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codifica = new javax.swing.JButton();
        firmaRadio = new javax.swing.JRadioButton();
        MACRadio = new javax.swing.JRadioButton();
        HashRadio = new javax.swing.JRadioButton();
        destinatarioText = new javax.swing.JTextField();
        mittenteText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codificaMSelect.setMaximumRowCount(3);
        codificaMSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AES", "DES", "DESede" }));
        codificaMSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codificaMSelectActionPerformed(evt);
            }
        });

        modiSelect.setMaximumRowCount(3);
        modiSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ECB", "CBC", "CFB" }));
        modiSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modiSelectActionPerformed(evt);
            }
        });

        dimRSASelect.setMaximumRowCount(2);
        dimRSASelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1024", "2048" }));

        paddingRSASelect.setMaximumRowCount(2);
        paddingRSASelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PKCS1", "OAEP" }));

        hashSelect.setMaximumRowCount(5);
        hashSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SHA-1", "SHA-224", "SHA-256", "SHA-384", "SHA-512" }));
        hashSelect.setEnabled(false);

        macSelect.setMaximumRowCount(3);
        macSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MD5", "SHA-256", "SHA-384" }));
        macSelect.setEnabled(false);

        dimDSASelect.setMaximumRowCount(2);
        dimDSASelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1024", "2048" }));

        DSASelect.setMaximumRowCount(3);
        DSASelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SHA1withDSA", "SHA224withDSA", "SHA256withDSA" }));

        jLabel1.setText("Codifica messaggio");

        jLabel2.setText("Modo operativo");

        jLabel3.setText("Dimensione RSA");

        jLabel4.setText("Padding RSA");

        jLabel5.setText("Hash");

        jLabel6.setText("MAC");

        jLabel7.setText("Firma ");

        jLabel8.setText("Dimensione firma");

        codifica.setText("Codifica");
        codifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codificaActionPerformed(evt);
            }
        });

        buttonGroup1.add(firmaRadio);
        firmaRadio.setSelected(true);
        firmaRadio.setText("Firma digitale");
        firmaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firmaRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(MACRadio);
        MACRadio.setText("MAC");

        buttonGroup1.add(HashRadio);
        HashRadio.setText("Hash");

        destinatarioText.setText("Destinatario");

        mittenteText.setText("Mittente");
        mittenteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mittenteTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codificaMSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modiSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firmaRadio)
                            .addComponent(MACRadio))))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dimRSASelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hashSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(macSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(paddingRSASelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(DSASelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(dimDSASelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(codifica))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinatarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mittenteText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HashRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codificaMSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dimRSASelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hashSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(macSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DSASelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(codifica))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modiSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paddingRSASelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dimDSASelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firmaRadio)
                    .addComponent(destinatarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MACRadio)
                    .addComponent(mittenteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HashRadio)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Codifica", jPanel2);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jButton1)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton1)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Decodifica", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codificaMSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codificaMSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codificaMSelectActionPerformed

    private void modiSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modiSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modiSelectActionPerformed

    private void codificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codificaActionPerformed
        // TODO add your handling code here:
        String mittente = mittenteText.getText();
        String destinatario = destinatarioText.getText();
        byte cifrario_m = (byte)codificaMSelect.getSelectedIndex();
        byte cifrario_k_dim = (byte)dimRSASelect.getSelectedIndex();
        byte padding = (byte)paddingRSASelect.getSelectedIndex();
        byte integrita;
        byte hash=0x08;
        byte mac=0x08;
        byte firma=0x08;
        byte dimFirma=0x08;
        if(firmaRadio.isSelected()){
            integrita = 0x00;
            hash=(byte)DSASelect.getSelectedIndex();
            hash=(byte)dimDSASelect.getSelectedIndex();
            
        } else if(MACRadio.isSelected()){
            integrita  = 0x01;
            hash=(byte)macSelect.getSelectedIndex();
        } else {
            integrita = 0x02;
            hash=(byte)hashSelect.getSelectedIndex();
        }
        byte modi_operativi = (byte)modiSelect.getSelectedIndex();
        
        
        System.out.println(mittente + " " + destinatario + " " + cifrario_m);
        NewFile f = new NewFile(mittente, destinatario, cifrario_m, 
                cifrario_k_dim, padding, integrita, null, modi_operativi, null, hash, mac, firma, dimFirma, null);
        try {
            f.codifica();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_codificaActionPerformed

    private void firmaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firmaRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firmaRadioActionPerformed

    private void mittenteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mittenteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mittenteTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DSASelect;
    private javax.swing.JRadioButton HashRadio;
    private javax.swing.JRadioButton MACRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton codifica;
    private javax.swing.JComboBox<String> codificaMSelect;
    private javax.swing.JTextField destinatarioText;
    private javax.swing.JComboBox<String> dimDSASelect;
    private javax.swing.JComboBox<String> dimRSASelect;
    private javax.swing.JRadioButton firmaRadio;
    private javax.swing.JComboBox<String> hashSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> macSelect;
    private javax.swing.JTextField mittenteText;
    private javax.swing.JComboBox<String> modiSelect;
    private javax.swing.JComboBox<String> paddingRSASelect;
    // End of variables declaration//GEN-END:variables
}
